name: Travel App

on:
  push:
    branches:
      - master

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run
